import "/app/styles/globals.scss"

import styles from "/app/home.module.scss";
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {getClientConfig} from "@/app/config/client";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <head>
            <meta name="config" content={JSON.stringify(getClientConfig())}/>
            <link rel="manifest" href="/site.webmanifest"></link>
        </head>
        <body className={"inter.className"}>
        <div className={styles.container}>
            {children}
        </div>
        </body>
        </html>
    )
}
